# Site Settings (Mediator Theme)
title: zeseung의 GitHub 블로그
description: 개발과 일상을 기록하는 블로그입니다.
logo: 'https://via.placeholder.com/300x300/333/fff?text=Z'
cover: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80'
name: 'zeseung'
email: your-email@example.com
author: zeseung
author_image: 'https://via.placeholder.com/300x300/57A3E8/fff?text=zeseung'

# Social Media Settings
social:
  - icon: twitter
    url: 
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: facebook
    url: 
    desc: Connect on facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: github-alt
    url: https://github.com/zeseung
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

# Advanced Settings
baseurl: ""
url: "https://zeseung.github.io"
google_analytics: # Google Analytics ID 입력

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
paginate_path: "/page:num/"

# Content paginator (disabled for compatibility)
# paginate_content:
#   enabled: true
#   debug: false
#   collections:
#     - posts
#   auto: false
#   separator: "--page-break--"
#   permalink: "/:num/"
#   seo_canonical: true
#   properties:
#     part:
#       is_generated: true
#     last:
#       is_generated: true
#     single:
#       is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Timezone
timezone: Asia/Seoul
date_format: "%Y년 %m월 %d일"

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/